class APP {
  static const USER_PROFILE = 'USER_PROFILE';
  static const BRAND_RESEARCH_CUSTOMIZATION_TAGS =
      'BRAND_RESEARCH_CUSTOMIZATION_TAGS';
  static const BRAND_RESEARCH_BRAND_LIST = 'BRAND_RESEARCH_BRAND_LIST';
  static const PRODUCT_RESEARCH_PRODUCT_LIST = 'PRODUCT_RESEARCH_PRODUCT_LIST';
  static const PRODUCT_RESEARCH_CUSTOMIZATION_TAGS =
      'PRODUC_RESEARCH_CUSTOMIZATION_TAGS';
  static const SELLER_RESEARCH_CUSTOMIZATION_TAGS =
      'SELLER_RESEARCH_CUSTOMIZATION_TAGS';
  static const SELLER_RESEARCH_SELLER_MY_LIST =
      'SELLER_RESEARCH_SELLER_MY_LIST';
  static const PRODUCT_RESEARCH_PRODUCT_MY_LIST =
      'PRODUCT_RESEARCH_PRODUCT_MY_LIST';
  static const REVENUE_CHART_FILTER_DATE_LIST =
      'REVENUE_CHART_FILTER_DATE_LIST';
  static const PRICE_AND_SALES_CHART_FILTER_DATE_LIST =
      'PRICE_AND_SALES_CHART_FILTER_DATE_LIST';
  static const REVIEW_AND_RATING_CHART_FILTER_DATE_LIST =
      'REVIEW_AND_RATING_CHART_FILTER_DATE_LIST';
  static const SELLERS_CHART_FILTER_DATE_LIST =
      'SELLERS_CHART_FILTER_DATE_LIST';
  static const BADGE_HISTORY_CHART_FILTER_DATE_LIST =
      'BADGE_HISTORY_CHART_FILTER_DATE_LIST';
  static const KEYWORD_RESEARCH_MY_LIST = 'KEYWORD_RESEARCH_MY_LIST';
  static const KEYWORD_RESEARCH_ITEM_LIST = 'KEYWORD_RESEARCH_ITEM_LIST';
  static const KEYWORD_HISTORY_LIST = 'KEYWORD_HISTORY_LIST';
  static const MISSPELLING_HISTORY_LIST = 'MISSPELLING_HISTORY_LIST';
  static const MISSPELLING_KEYWORD_LIST = 'MISSPELLING_KEYWORD_LIST';
  static const KEYWORD_RESERVE_ASIN_LIST = 'KEYWORD_RESERVE_ASIN_LIST';
}
